### ISSUE TITLE
HTTPS prevents history graph from displaying

### ISSUE THREAD

**Issue by victorypoint** [pljones/jamulus-historytool#2]
Hi Peter. I just discovered this issue. while enabling HTTPS on my Jamulus stats website. When displaying the history tool test page at http://victorypoint.ddns.net/jamulus_history/, the graph works fine. However, the history graph doesn't display via an HTTPS connection to the same page at https://victorypoint.ddns.net/jamulus_history/.

**Comment by pljones** [comment]
Have you checked your web server logs?

**Comment by victorypoint** [comment]
I did but no errors were logged (running nginx). I ran 'find /var/log -type f -mmin -5 -ls' to see if other logs recorded an error but nothing.

**Comment by victorypoint** [comment]
Got it working. Solution is to remove 'http:' at beginning of these lines in index.html:
```
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.1/jquery.min.js"></script>
<script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.13/jquery-ui.min.js"></script>
```

I also made this change to /js/history_controller.js - add .php extension to jamulus_history' in last line:

`update_graph(base + '/php/jamulus_history.php?days=' + hg_days + '&reverse=false', 60000);`

**Comment by pljones** [comment]
Ah - the `.php` is probably very relevant.  I've a hack in my apache config for that...  I always forget it's there and when I build a new machine, I always forget to add it and nothing works for days...

Is it all working now?

**Comment by victorypoint** [comment]
Yes, all good now from what I can tell on both of my https sites. Thanks! Great code.

https://victorypoint.ddns.net/
https://studiovancouver.ddns.net/

**Comment by pljones** [comment]
OK, I'll close this then.
